[server]
  host = "localhost"
  bind_ip = "0.0.0.0"
  nonssl = 10000
  cookie_secret = "medbookCookie change for production"
  pingIntervalMS = 2000
  uid = "galaxy"

[apps]
   [apps.WB]
   auth = false
   route = "/wb"
   cwd = "../MedBook-Workbench"
   run = "/bin/sh -c ./run"
   port = 10003
   menuPosition = 0
   menuItem = "Workbench"

   [apps.CRFs]
   auth = false
   route = "/CRF"
   cwd = "../MedBook-CRFs/"
   run = "/bin/sh -c ./run.sh"
   port = 3000
   menuPosition = 1
   menuItem = "Forms"
   containerName = "crfs"

   [apps.Telescope]
   auth = false
   route = "/"
   menuPosition = 3
   menuItem = "Telescope"
   containerName = "telescope"
   port = 3000

   [apps.galaxy]
   auth = false
   route = "/galaxy"
   cwd = "../galaxy-dist"
   run = "/bin/sh -c ./run"
   port = 10010
   menuPosition = 4
   menuItem = "Galaxy"

   [apps.fusion]
   auth = false
   route = "/fusion"
   cwd = "../Medbook-Fusion5"
   ping = "/fusion/packages/reload.js"
   run = "/bin/sh -c ./run"
   port = 10011
   menuPosition = 5
   menuItem = "Data Fusion"


   [apps.cbioportal]
   auth = true
   route = "/cbioportal"
   port = 8585
   menuItem = "Cbioportal"

[final]
   redirect = "/"
   cwd = "../MedBook-Telescope3"
   run = "/bin/sh -c ./rundev"
   port = 10001

