[server]
bind_ip = "0.0.0.0"
bind_port = 10000
cookie_secret = "medbookCookie change for production"
# google apps domain
auth_domain = ""

[domains]
  [domains.example1]
  host = "su2c-dev.ucsc.edu:10000"
  upstream = [ "su2c-dev.ucsc.edu:8081"]

[apps]
   [apps.WB]
   auth = false
   route = "/wb"
   run = "./Telescope/run 10003"
   port = 10003
   menuPosition = 0
   menuItem = "WB"

   [apps.CRFs]
   auth = false
   route = "/CRF"
   run = "./CRF/run 10002"
   port = 10002
   menuPosition = 1
   menuItem = "Forms"

   [apps.Telescope]
   auth = false
   route = "/tel"
   run = "./Telescope/run 10001"
   port = 10001
   menuPosition = 3
   menuItem = "Telescope"

   [apps.demoPost]
   auth = false
   route = "/demoPost"
   run = "./Telescope/run 20004"
   port = 20004
   menuPosition = 1
   menuItem = "Demo Post"


   [apps.fileupload]
   auth = false
   route = "/fileupload"
   run = "./Apps/fileupload/run 22222"
   port = 22222
   menuPosition = 3
   menuItem = "File Upload"

   [apps.galaxy]
   auth = true
   route = "/galaxy"
   run = "./galaxy-central/run"
   port = 10010
   menuPosition = 4
   menuItem = "Galaxy"

   [apps.Admin]
   auth = true
   route = "/admin"
   run = "./Apps/flat/run 10005"
   port = 10005
   menuPosition = 0
   menuItem = "Admin"


   [apps.cbioportal]
   auth = true
   route = "/cbioportal"
   run = ""
   port = 8585
   menuItem = "CBioPortal"

   [apps.flat]
   auth = true
   route = "/flat"
   run = "./Apps/flat/run 22222"
   port = 22222
   menuItem = "Flat"

[final]
   redirect = "/"
   run = "./Telescope/run 10001"
   port = 10001

