[server]
bind_ip = "0.0.0.0"
bind_port = 10000
cookie_secret = "medbookCookie"
# google apps domain
auth_domain = ""

[domains]
  [domains.example1]
  host = "su2c-dev.ucsc.edu:10000"
  upstream = [ "su2c-dev.ucsc.edu:8081"]
  client_id = "210653342985.apps.googleusercontent.com"
  client_secret = "tRD12MAYeFxVZOYkgqKK8AoP"

[apps]
   [apps.Telescope]
   auth = false
   route = "/tel"
   run = "./Telescope/run 10005"
   port = 10005

   [apps.fileupload]
   auth = true
   route = "/fileupload"
   run = "./Apps/fileupload/run 22222"
   port = 22222

   [apps.galaxy]
   auth = true
   route = "/galaxy"
   run = "./galaxy-central/run"
   port = 10010

   [apps.cbioportal]
   auth = true
   route = "/cbioportal"
   run = ""
   port = 8585

   [apps.hello]
   auth = false
   route = "/hello"
   run = "./Apps/hello/run 10002"
   port = 10002

   [apps.flat]
   auth = true
   route = "/flat"
   run = "./Apps/flat/run 22222"
   port = 22222

[final]
   redirect = "/tel"

